/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.14.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QProgressBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QLabel *ErrorLabel;
    QPushButton *DebugButton;
    QGroupBox *status_groupBox;
    QVBoxLayout *verticalLayout_5;
    QCheckBox *internalMemTest_checkBox;
    QCheckBox *incompatibleASICorDMD_checkBox;
    QCheckBox *slaveReady_checkBox;
    QCheckBox *internalInit_checkBox;
    QCheckBox *DMDResetWaveformControllerErr_checkBox;
    QCheckBox *forcedSwapErr_checkBox;
    QCheckBox *seqAbortStatus_checkBox;
    QCheckBox *seqErr_checkBox;
    QCheckBox *DMDParkStatus_checkBox;
    QCheckBox *sequencerRunState_checkBox;
    QCheckBox *videoState_checkBox;
    QCheckBox *extSourceLocked_checkBox;
    QGroupBox *DMDgroupBox;
    QComboBox *darkTimeUnitComboBox;
    QLabel *label;
    QSpinBox *expoTimeSpinBox;
    QLabel *label_2;
    QComboBox *expoTimeUnitComboBox;
    QSpinBox *darkTimeSpinBox;
    QPushButton *ClearPatternsButton;
    QPushButton *UpdateLUTButton;
    QPushButton *startPatSequenceButton;
    QPushButton *stopPatSequenceButton;
    QPushButton *pausePatSequenceButton;
    QPushButton *AddPatternsButton;
    QCheckBox *DMDConnectCheckBox;
    QPushButton *DMDConnectButton;
    QCheckBox *DMDRepeatCheckBox;
    QCheckBox *DMDPlayOnceCheckBox;
    QCheckBox *DMDTrigInCheckBox;
    QCheckBox *DMDTrigOutCheckBox;
    QGroupBox *stageGroupBox;
    QGroupBox *groupBox;
    QLabel *zPosLabel;
    QLabel *label_4;
    QLabel *label_12;
    QDoubleSpinBox *zStepDoubleSpinBox;
    QLabel *label_3;
    QComboBox *zStepUnitComboBox;
    QLabel *label_5;
    QPushButton *zAddButton;
    QPushButton *zMinusButton;
    QDoubleSpinBox *zTargetDoubleSpinBox;
    QLabel *label_16;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *label_19;
    QDoubleSpinBox *zVelocityDoubleSpinBox;
    QPushButton *zVelocityMoveButton;
    QPushButton *zStopButton;
    QPushButton *zTargetMoveButton;
    QGroupBox *groupBox_2;
    QLabel *xPosLabel;
    QLabel *label_8;
    QComboBox *xStepUnitComboBox;
    QLabel *label_7;
    QLabel *label_13;
    QDoubleSpinBox *xStepDoubleSpinBox;
    QLabel *label_6;
    QPushButton *xMinusButton;
    QPushButton *xAddButton;
    QLabel *label_20;
    QLabel *label_21;
    QDoubleSpinBox *xTargetDoubleSpinBox;
    QPushButton *xTargetMoveButton;
    QGroupBox *groupBox_3;
    QLabel *yPosLabel;
    QLabel *label_14;
    QLabel *label_11;
    QDoubleSpinBox *yStepDoubleSpinBox;
    QComboBox *yStepUnitComboBox;
    QLabel *label_9;
    QLabel *label_10;
    QPushButton *yMinusButton;
    QPushButton *yAddButton;
    QPushButton *yTargetMoveButton;
    QDoubleSpinBox *yTargetDoubleSpinBox;
    QLabel *label_22;
    QLabel *label_23;
    QCheckBox *stageConnectCheckBox;
    QPushButton *stageConnectButton;
    QListWidget *listWidget;
    QGroupBox *groupBox_4;
    QLabel *label_27;
    QCheckBox *StepMoveCheckBox;
    QLabel *label_24;
    QPushButton *stopLayerPrintButton;
    QLabel *label_25;
    QPushButton *startLayerPrintButton;
    QSpinBox *LayerNumberSpinBox;
    QCheckBox *VelocityMoveCheckBox;
    QDoubleSpinBox *LayerHeightDoubleSpinBox;
    QDoubleSpinBox *StructHeightDoubleSpinBox;
    QLabel *label_15;
    QLabel *label_26;
    QLabel *label_28;
    QProgressBar *PrintProgressBar;
    QPushButton *savePatternConfigurationButton;
    QPushButton *loadPatternConfigurationButton;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1104, 716);
        QFont font;
        font.setPointSize(10);
        MainWindow->setFont(font);
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/icon/LP.ico"), QSize(), QIcon::Normal, QIcon::Off);
        MainWindow->setWindowIcon(icon);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        ErrorLabel = new QLabel(centralwidget);
        ErrorLabel->setObjectName(QString::fromUtf8("ErrorLabel"));
        ErrorLabel->setGeometry(QRect(0, 650, 1000, 30));
        ErrorLabel->setFont(font);
        ErrorLabel->setFrameShape(QFrame::NoFrame);
        ErrorLabel->setFrameShadow(QFrame::Plain);
        DebugButton = new QPushButton(centralwidget);
        DebugButton->setObjectName(QString::fromUtf8("DebugButton"));
        DebugButton->setGeometry(QRect(0, 620, 120, 30));
        status_groupBox = new QGroupBox(centralwidget);
        status_groupBox->setObjectName(QString::fromUtf8("status_groupBox"));
        status_groupBox->setEnabled(false);
        status_groupBox->setGeometry(QRect(880, 590, 221, 271));
        QSizePolicy sizePolicy(QSizePolicy::Fixed, QSizePolicy::Fixed);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(status_groupBox->sizePolicy().hasHeightForWidth());
        status_groupBox->setSizePolicy(sizePolicy);
        status_groupBox->setStyleSheet(QString::fromUtf8("QGroupBox{ border: 1px solid ;\n"
"background-color: transparent;\n"
"border-color: rgb(0,150,150);\n"
"color:rgb(0,120,120);\n"
";}"));
        verticalLayout_5 = new QVBoxLayout(status_groupBox);
        verticalLayout_5->setObjectName(QString::fromUtf8("verticalLayout_5"));
        verticalLayout_5->setContentsMargins(-1, 20, -1, -1);
        internalMemTest_checkBox = new QCheckBox(status_groupBox);
        internalMemTest_checkBox->setObjectName(QString::fromUtf8("internalMemTest_checkBox"));

        verticalLayout_5->addWidget(internalMemTest_checkBox);

        incompatibleASICorDMD_checkBox = new QCheckBox(status_groupBox);
        incompatibleASICorDMD_checkBox->setObjectName(QString::fromUtf8("incompatibleASICorDMD_checkBox"));

        verticalLayout_5->addWidget(incompatibleASICorDMD_checkBox);

        slaveReady_checkBox = new QCheckBox(status_groupBox);
        slaveReady_checkBox->setObjectName(QString::fromUtf8("slaveReady_checkBox"));

        verticalLayout_5->addWidget(slaveReady_checkBox);

        internalInit_checkBox = new QCheckBox(status_groupBox);
        internalInit_checkBox->setObjectName(QString::fromUtf8("internalInit_checkBox"));

        verticalLayout_5->addWidget(internalInit_checkBox);

        DMDResetWaveformControllerErr_checkBox = new QCheckBox(status_groupBox);
        DMDResetWaveformControllerErr_checkBox->setObjectName(QString::fromUtf8("DMDResetWaveformControllerErr_checkBox"));

        verticalLayout_5->addWidget(DMDResetWaveformControllerErr_checkBox);

        forcedSwapErr_checkBox = new QCheckBox(status_groupBox);
        forcedSwapErr_checkBox->setObjectName(QString::fromUtf8("forcedSwapErr_checkBox"));

        verticalLayout_5->addWidget(forcedSwapErr_checkBox);

        seqAbortStatus_checkBox = new QCheckBox(status_groupBox);
        seqAbortStatus_checkBox->setObjectName(QString::fromUtf8("seqAbortStatus_checkBox"));

        verticalLayout_5->addWidget(seqAbortStatus_checkBox);

        seqErr_checkBox = new QCheckBox(status_groupBox);
        seqErr_checkBox->setObjectName(QString::fromUtf8("seqErr_checkBox"));

        verticalLayout_5->addWidget(seqErr_checkBox);

        DMDParkStatus_checkBox = new QCheckBox(status_groupBox);
        DMDParkStatus_checkBox->setObjectName(QString::fromUtf8("DMDParkStatus_checkBox"));

        verticalLayout_5->addWidget(DMDParkStatus_checkBox);

        sequencerRunState_checkBox = new QCheckBox(status_groupBox);
        sequencerRunState_checkBox->setObjectName(QString::fromUtf8("sequencerRunState_checkBox"));

        verticalLayout_5->addWidget(sequencerRunState_checkBox);

        videoState_checkBox = new QCheckBox(status_groupBox);
        videoState_checkBox->setObjectName(QString::fromUtf8("videoState_checkBox"));

        verticalLayout_5->addWidget(videoState_checkBox);

        extSourceLocked_checkBox = new QCheckBox(status_groupBox);
        extSourceLocked_checkBox->setObjectName(QString::fromUtf8("extSourceLocked_checkBox"));

        verticalLayout_5->addWidget(extSourceLocked_checkBox);

        DMDgroupBox = new QGroupBox(centralwidget);
        DMDgroupBox->setObjectName(QString::fromUtf8("DMDgroupBox"));
        DMDgroupBox->setGeometry(QRect(450, 10, 311, 341));
        QFont font1;
        font1.setPointSize(11);
        font1.setBold(true);
        font1.setWeight(75);
        DMDgroupBox->setFont(font1);
        darkTimeUnitComboBox = new QComboBox(DMDgroupBox);
        darkTimeUnitComboBox->setObjectName(QString::fromUtf8("darkTimeUnitComboBox"));
        darkTimeUnitComboBox->setGeometry(QRect(200, 120, 60, 22));
        QFont font2;
        font2.setPointSize(10);
        font2.setBold(false);
        font2.setWeight(50);
        darkTimeUnitComboBox->setFont(font2);
        label = new QLabel(DMDgroupBox);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(10, 80, 75, 22));
        QFont font3;
        font3.setPointSize(10);
        font3.setBold(false);
        font3.setWeight(50);
        font3.setKerning(true);
        label->setFont(font3);
        label->setFocusPolicy(Qt::NoFocus);
        label->setLayoutDirection(Qt::LeftToRight);
        label->setAlignment(Qt::AlignCenter);
        expoTimeSpinBox = new QSpinBox(DMDgroupBox);
        expoTimeSpinBox->setObjectName(QString::fromUtf8("expoTimeSpinBox"));
        expoTimeSpinBox->setGeometry(QRect(90, 80, 101, 22));
        expoTimeSpinBox->setFont(font2);
        label_2 = new QLabel(DMDgroupBox);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(10, 120, 75, 22));
        label_2->setFont(font3);
        label_2->setFocusPolicy(Qt::NoFocus);
        label_2->setLayoutDirection(Qt::LeftToRight);
        label_2->setAlignment(Qt::AlignCenter);
        expoTimeUnitComboBox = new QComboBox(DMDgroupBox);
        expoTimeUnitComboBox->setObjectName(QString::fromUtf8("expoTimeUnitComboBox"));
        expoTimeUnitComboBox->setGeometry(QRect(200, 80, 60, 22));
        expoTimeUnitComboBox->setFont(font2);
        darkTimeSpinBox = new QSpinBox(DMDgroupBox);
        darkTimeSpinBox->setObjectName(QString::fromUtf8("darkTimeSpinBox"));
        darkTimeSpinBox->setGeometry(QRect(90, 120, 101, 22));
        darkTimeSpinBox->setFont(font2);
        ClearPatternsButton = new QPushButton(DMDgroupBox);
        ClearPatternsButton->setObjectName(QString::fromUtf8("ClearPatternsButton"));
        ClearPatternsButton->setGeometry(QRect(30, 260, 90, 30));
        ClearPatternsButton->setFont(font2);
        UpdateLUTButton = new QPushButton(DMDgroupBox);
        UpdateLUTButton->setObjectName(QString::fromUtf8("UpdateLUTButton"));
        UpdateLUTButton->setGeometry(QRect(30, 300, 90, 30));
        UpdateLUTButton->setFont(font2);
        startPatSequenceButton = new QPushButton(DMDgroupBox);
        startPatSequenceButton->setObjectName(QString::fromUtf8("startPatSequenceButton"));
        startPatSequenceButton->setGeometry(QRect(160, 220, 90, 30));
        QFont font4;
        font4.setPointSize(10);
        font4.setBold(false);
        font4.setItalic(false);
        font4.setUnderline(false);
        font4.setWeight(50);
        startPatSequenceButton->setFont(font4);
        stopPatSequenceButton = new QPushButton(DMDgroupBox);
        stopPatSequenceButton->setObjectName(QString::fromUtf8("stopPatSequenceButton"));
        stopPatSequenceButton->setGeometry(QRect(160, 300, 90, 30));
        stopPatSequenceButton->setFont(font2);
        pausePatSequenceButton = new QPushButton(DMDgroupBox);
        pausePatSequenceButton->setObjectName(QString::fromUtf8("pausePatSequenceButton"));
        pausePatSequenceButton->setGeometry(QRect(160, 260, 90, 30));
        pausePatSequenceButton->setFont(font2);
        AddPatternsButton = new QPushButton(DMDgroupBox);
        AddPatternsButton->setObjectName(QString::fromUtf8("AddPatternsButton"));
        AddPatternsButton->setGeometry(QRect(30, 220, 90, 30));
        AddPatternsButton->setFont(font2);
        DMDConnectCheckBox = new QCheckBox(DMDgroupBox);
        DMDConnectCheckBox->setObjectName(QString::fromUtf8("DMDConnectCheckBox"));
        DMDConnectCheckBox->setEnabled(false);
        DMDConnectCheckBox->setGeometry(QRect(130, 40, 75, 30));
        DMDConnectCheckBox->setFont(font2);
        DMDConnectButton = new QPushButton(DMDgroupBox);
        DMDConnectButton->setObjectName(QString::fromUtf8("DMDConnectButton"));
        DMDConnectButton->setGeometry(QRect(20, 40, 90, 30));
        DMDConnectButton->setFont(font2);
        DMDRepeatCheckBox = new QCheckBox(DMDgroupBox);
        DMDRepeatCheckBox->setObjectName(QString::fromUtf8("DMDRepeatCheckBox"));
        DMDRepeatCheckBox->setEnabled(true);
        DMDRepeatCheckBox->setGeometry(QRect(40, 150, 75, 30));
        DMDRepeatCheckBox->setFont(font2);
        DMDPlayOnceCheckBox = new QCheckBox(DMDgroupBox);
        DMDPlayOnceCheckBox->setObjectName(QString::fromUtf8("DMDPlayOnceCheckBox"));
        DMDPlayOnceCheckBox->setEnabled(true);
        DMDPlayOnceCheckBox->setGeometry(QRect(160, 150, 75, 30));
        DMDPlayOnceCheckBox->setFont(font2);
        DMDTrigInCheckBox = new QCheckBox(DMDgroupBox);
        DMDTrigInCheckBox->setObjectName(QString::fromUtf8("DMDTrigInCheckBox"));
        DMDTrigInCheckBox->setEnabled(true);
        DMDTrigInCheckBox->setGeometry(QRect(40, 180, 75, 30));
        DMDTrigInCheckBox->setFont(font2);
        DMDTrigOutCheckBox = new QCheckBox(DMDgroupBox);
        DMDTrigOutCheckBox->setObjectName(QString::fromUtf8("DMDTrigOutCheckBox"));
        DMDTrigOutCheckBox->setEnabled(true);
        DMDTrigOutCheckBox->setGeometry(QRect(160, 180, 101, 30));
        DMDTrigOutCheckBox->setFont(font2);
        stageGroupBox = new QGroupBox(centralwidget);
        stageGroupBox->setObjectName(QString::fromUtf8("stageGroupBox"));
        stageGroupBox->setGeometry(QRect(10, 10, 431, 521));
        stageGroupBox->setFont(font1);
        groupBox = new QGroupBox(stageGroupBox);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(10, 100, 411, 141));
        groupBox->setFont(font2);
        zPosLabel = new QLabel(groupBox);
        zPosLabel->setObjectName(QString::fromUtf8("zPosLabel"));
        zPosLabel->setGeometry(QRect(119, 70, 101, 22));
        zPosLabel->setFont(font3);
        zPosLabel->setFocusPolicy(Qt::NoFocus);
        zPosLabel->setLayoutDirection(Qt::LeftToRight);
        zPosLabel->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_4 = new QLabel(groupBox);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(39, 70, 75, 22));
        label_4->setFont(font3);
        label_4->setFocusPolicy(Qt::NoFocus);
        label_4->setLayoutDirection(Qt::LeftToRight);
        label_4->setAlignment(Qt::AlignCenter);
        label_12 = new QLabel(groupBox);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(230, 70, 61, 22));
        label_12->setFont(font3);
        label_12->setFocusPolicy(Qt::NoFocus);
        label_12->setLayoutDirection(Qt::LeftToRight);
        label_12->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        zStepDoubleSpinBox = new QDoubleSpinBox(groupBox);
        zStepDoubleSpinBox->setObjectName(QString::fromUtf8("zStepDoubleSpinBox"));
        zStepDoubleSpinBox->setGeometry(QRect(120, 10, 101, 22));
        zStepDoubleSpinBox->setDecimals(3);
        zStepDoubleSpinBox->setMaximum(1000000000.000000000000000);
        label_3 = new QLabel(groupBox);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(40, 10, 75, 22));
        label_3->setFont(font3);
        label_3->setFocusPolicy(Qt::NoFocus);
        label_3->setLayoutDirection(Qt::LeftToRight);
        label_3->setAlignment(Qt::AlignCenter);
        zStepUnitComboBox = new QComboBox(groupBox);
        zStepUnitComboBox->setObjectName(QString::fromUtf8("zStepUnitComboBox"));
        zStepUnitComboBox->setGeometry(QRect(230, 10, 60, 22));
        label_5 = new QLabel(groupBox);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(4, 24, 51, 22));
        QFont font5;
        font5.setPointSize(12);
        font5.setBold(false);
        font5.setWeight(50);
        font5.setKerning(true);
        label_5->setFont(font5);
        label_5->setFocusPolicy(Qt::NoFocus);
        label_5->setLayoutDirection(Qt::LeftToRight);
        label_5->setAlignment(Qt::AlignCenter);
        zAddButton = new QPushButton(groupBox);
        zAddButton->setObjectName(QString::fromUtf8("zAddButton"));
        zAddButton->setGeometry(QRect(300, 10, 41, 51));
        QFont font6;
        font6.setPointSize(18);
        font6.setBold(false);
        font6.setWeight(50);
        zAddButton->setFont(font6);
        zMinusButton = new QPushButton(groupBox);
        zMinusButton->setObjectName(QString::fromUtf8("zMinusButton"));
        zMinusButton->setGeometry(QRect(350, 10, 41, 51));
        zMinusButton->setFont(font6);
        zTargetDoubleSpinBox = new QDoubleSpinBox(groupBox);
        zTargetDoubleSpinBox->setObjectName(QString::fromUtf8("zTargetDoubleSpinBox"));
        zTargetDoubleSpinBox->setGeometry(QRect(120, 40, 101, 22));
        zTargetDoubleSpinBox->setDecimals(3);
        zTargetDoubleSpinBox->setMaximum(250.000000000000000);
        label_16 = new QLabel(groupBox);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(40, 40, 75, 22));
        label_16->setFont(font3);
        label_16->setFocusPolicy(Qt::NoFocus);
        label_16->setLayoutDirection(Qt::LeftToRight);
        label_16->setAlignment(Qt::AlignCenter);
        label_17 = new QLabel(groupBox);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(230, 40, 61, 22));
        label_17->setFont(font3);
        label_17->setFocusPolicy(Qt::NoFocus);
        label_17->setLayoutDirection(Qt::LeftToRight);
        label_17->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_18 = new QLabel(groupBox);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(230, 100, 61, 22));
        label_18->setFont(font3);
        label_18->setFocusPolicy(Qt::NoFocus);
        label_18->setLayoutDirection(Qt::LeftToRight);
        label_18->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_19 = new QLabel(groupBox);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(40, 100, 75, 22));
        label_19->setFont(font3);
        label_19->setFocusPolicy(Qt::NoFocus);
        label_19->setLayoutDirection(Qt::LeftToRight);
        label_19->setAlignment(Qt::AlignCenter);
        zVelocityDoubleSpinBox = new QDoubleSpinBox(groupBox);
        zVelocityDoubleSpinBox->setObjectName(QString::fromUtf8("zVelocityDoubleSpinBox"));
        zVelocityDoubleSpinBox->setGeometry(QRect(120, 100, 101, 22));
        zVelocityDoubleSpinBox->setDecimals(3);
        zVelocityDoubleSpinBox->setMinimum(-1000.000000000000000);
        zVelocityDoubleSpinBox->setMaximum(1000000.000000000000000);
        zVelocityMoveButton = new QPushButton(groupBox);
        zVelocityMoveButton->setObjectName(QString::fromUtf8("zVelocityMoveButton"));
        zVelocityMoveButton->setGeometry(QRect(300, 70, 91, 23));
        zStopButton = new QPushButton(groupBox);
        zStopButton->setObjectName(QString::fromUtf8("zStopButton"));
        zStopButton->setGeometry(QRect(300, 100, 91, 23));
        zTargetMoveButton = new QPushButton(groupBox);
        zTargetMoveButton->setObjectName(QString::fromUtf8("zTargetMoveButton"));
        zTargetMoveButton->setGeometry(QRect(260, 40, 31, 23));
        QIcon icon1;
        icon1.addFile(QString::fromUtf8("Icon/enter.png"), QSize(), QIcon::Normal, QIcon::Off);
        zTargetMoveButton->setIcon(icon1);
        groupBox_2 = new QGroupBox(stageGroupBox);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(10, 270, 411, 101));
        groupBox_2->setFont(font2);
        xPosLabel = new QLabel(groupBox_2);
        xPosLabel->setObjectName(QString::fromUtf8("xPosLabel"));
        xPosLabel->setGeometry(QRect(120, 70, 101, 22));
        xPosLabel->setFont(font3);
        xPosLabel->setFocusPolicy(Qt::NoFocus);
        xPosLabel->setLayoutDirection(Qt::LeftToRight);
        xPosLabel->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_8 = new QLabel(groupBox_2);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(40, 10, 75, 22));
        label_8->setFont(font3);
        label_8->setFocusPolicy(Qt::NoFocus);
        label_8->setLayoutDirection(Qt::LeftToRight);
        label_8->setAlignment(Qt::AlignCenter);
        xStepUnitComboBox = new QComboBox(groupBox_2);
        xStepUnitComboBox->setObjectName(QString::fromUtf8("xStepUnitComboBox"));
        xStepUnitComboBox->setGeometry(QRect(229, 10, 60, 22));
        label_7 = new QLabel(groupBox_2);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(40, 70, 75, 22));
        label_7->setFont(font3);
        label_7->setFocusPolicy(Qt::NoFocus);
        label_7->setLayoutDirection(Qt::LeftToRight);
        label_7->setAlignment(Qt::AlignCenter);
        label_13 = new QLabel(groupBox_2);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(230, 70, 75, 22));
        label_13->setFont(font3);
        label_13->setFocusPolicy(Qt::NoFocus);
        label_13->setLayoutDirection(Qt::LeftToRight);
        label_13->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        xStepDoubleSpinBox = new QDoubleSpinBox(groupBox_2);
        xStepDoubleSpinBox->setObjectName(QString::fromUtf8("xStepDoubleSpinBox"));
        xStepDoubleSpinBox->setGeometry(QRect(120, 10, 101, 22));
        xStepDoubleSpinBox->setDecimals(3);
        xStepDoubleSpinBox->setMaximum(1000000000.000000000000000);
        label_6 = new QLabel(groupBox_2);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(4, 24, 51, 22));
        label_6->setFont(font5);
        label_6->setFocusPolicy(Qt::NoFocus);
        label_6->setLayoutDirection(Qt::LeftToRight);
        label_6->setAlignment(Qt::AlignCenter);
        xMinusButton = new QPushButton(groupBox_2);
        xMinusButton->setObjectName(QString::fromUtf8("xMinusButton"));
        xMinusButton->setGeometry(QRect(350, 10, 41, 51));
        QFont font7;
        font7.setPointSize(18);
        xMinusButton->setFont(font7);
        xAddButton = new QPushButton(groupBox_2);
        xAddButton->setObjectName(QString::fromUtf8("xAddButton"));
        xAddButton->setGeometry(QRect(300, 10, 41, 51));
        xAddButton->setFont(font7);
        label_20 = new QLabel(groupBox_2);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(230, 40, 61, 22));
        label_20->setFont(font3);
        label_20->setFocusPolicy(Qt::NoFocus);
        label_20->setLayoutDirection(Qt::LeftToRight);
        label_20->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_21 = new QLabel(groupBox_2);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(40, 40, 75, 22));
        label_21->setFont(font3);
        label_21->setFocusPolicy(Qt::NoFocus);
        label_21->setLayoutDirection(Qt::LeftToRight);
        label_21->setAlignment(Qt::AlignCenter);
        xTargetDoubleSpinBox = new QDoubleSpinBox(groupBox_2);
        xTargetDoubleSpinBox->setObjectName(QString::fromUtf8("xTargetDoubleSpinBox"));
        xTargetDoubleSpinBox->setGeometry(QRect(120, 40, 101, 22));
        xTargetDoubleSpinBox->setDecimals(3);
        xTargetDoubleSpinBox->setMaximum(250.000000000000000);
        xTargetMoveButton = new QPushButton(groupBox_2);
        xTargetMoveButton->setObjectName(QString::fromUtf8("xTargetMoveButton"));
        xTargetMoveButton->setGeometry(QRect(260, 40, 31, 23));
        xTargetMoveButton->setIcon(icon1);
        groupBox_3 = new QGroupBox(stageGroupBox);
        groupBox_3->setObjectName(QString::fromUtf8("groupBox_3"));
        groupBox_3->setGeometry(QRect(10, 400, 411, 101));
        groupBox_3->setFont(font2);
        yPosLabel = new QLabel(groupBox_3);
        yPosLabel->setObjectName(QString::fromUtf8("yPosLabel"));
        yPosLabel->setGeometry(QRect(120, 70, 101, 22));
        yPosLabel->setFont(font3);
        yPosLabel->setFocusPolicy(Qt::NoFocus);
        yPosLabel->setLayoutDirection(Qt::LeftToRight);
        yPosLabel->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_14 = new QLabel(groupBox_3);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(231, 70, 75, 22));
        label_14->setFont(font3);
        label_14->setFocusPolicy(Qt::NoFocus);
        label_14->setLayoutDirection(Qt::LeftToRight);
        label_14->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_11 = new QLabel(groupBox_3);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(4, 24, 51, 22));
        label_11->setFont(font5);
        label_11->setFocusPolicy(Qt::NoFocus);
        label_11->setLayoutDirection(Qt::LeftToRight);
        label_11->setAlignment(Qt::AlignCenter);
        yStepDoubleSpinBox = new QDoubleSpinBox(groupBox_3);
        yStepDoubleSpinBox->setObjectName(QString::fromUtf8("yStepDoubleSpinBox"));
        yStepDoubleSpinBox->setGeometry(QRect(120, 10, 101, 22));
        yStepDoubleSpinBox->setDecimals(3);
        yStepDoubleSpinBox->setMaximum(1000000000.000000000000000);
        yStepUnitComboBox = new QComboBox(groupBox_3);
        yStepUnitComboBox->setObjectName(QString::fromUtf8("yStepUnitComboBox"));
        yStepUnitComboBox->setGeometry(QRect(230, 10, 60, 22));
        label_9 = new QLabel(groupBox_3);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(40, 10, 75, 22));
        label_9->setFont(font3);
        label_9->setFocusPolicy(Qt::NoFocus);
        label_9->setLayoutDirection(Qt::LeftToRight);
        label_9->setAlignment(Qt::AlignCenter);
        label_10 = new QLabel(groupBox_3);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(40, 70, 75, 22));
        label_10->setFont(font3);
        label_10->setFocusPolicy(Qt::NoFocus);
        label_10->setLayoutDirection(Qt::LeftToRight);
        label_10->setAlignment(Qt::AlignCenter);
        yMinusButton = new QPushButton(groupBox_3);
        yMinusButton->setObjectName(QString::fromUtf8("yMinusButton"));
        yMinusButton->setGeometry(QRect(350, 10, 41, 51));
        yMinusButton->setFont(font7);
        yAddButton = new QPushButton(groupBox_3);
        yAddButton->setObjectName(QString::fromUtf8("yAddButton"));
        yAddButton->setGeometry(QRect(300, 10, 41, 51));
        yAddButton->setFont(font7);
        yTargetMoveButton = new QPushButton(groupBox_3);
        yTargetMoveButton->setObjectName(QString::fromUtf8("yTargetMoveButton"));
        yTargetMoveButton->setGeometry(QRect(260, 40, 31, 23));
        yTargetMoveButton->setIcon(icon1);
        yTargetDoubleSpinBox = new QDoubleSpinBox(groupBox_3);
        yTargetDoubleSpinBox->setObjectName(QString::fromUtf8("yTargetDoubleSpinBox"));
        yTargetDoubleSpinBox->setGeometry(QRect(120, 40, 101, 22));
        yTargetDoubleSpinBox->setDecimals(3);
        yTargetDoubleSpinBox->setMaximum(250.000000000000000);
        label_22 = new QLabel(groupBox_3);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(40, 40, 75, 22));
        label_22->setFont(font3);
        label_22->setFocusPolicy(Qt::NoFocus);
        label_22->setLayoutDirection(Qt::LeftToRight);
        label_22->setAlignment(Qt::AlignCenter);
        label_23 = new QLabel(groupBox_3);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(230, 40, 61, 22));
        label_23->setFont(font3);
        label_23->setFocusPolicy(Qt::NoFocus);
        label_23->setLayoutDirection(Qt::LeftToRight);
        label_23->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_23->raise();
        yPosLabel->raise();
        label_14->raise();
        label_11->raise();
        yStepDoubleSpinBox->raise();
        yStepUnitComboBox->raise();
        label_9->raise();
        label_10->raise();
        yMinusButton->raise();
        yAddButton->raise();
        yTargetMoveButton->raise();
        yTargetDoubleSpinBox->raise();
        label_22->raise();
        stageConnectCheckBox = new QCheckBox(stageGroupBox);
        stageConnectCheckBox->setObjectName(QString::fromUtf8("stageConnectCheckBox"));
        stageConnectCheckBox->setEnabled(false);
        stageConnectCheckBox->setGeometry(QRect(130, 40, 75, 30));
        stageConnectCheckBox->setFont(font2);
        stageConnectButton = new QPushButton(stageGroupBox);
        stageConnectButton->setObjectName(QString::fromUtf8("stageConnectButton"));
        stageConnectButton->setGeometry(QRect(20, 40, 90, 30));
        stageConnectButton->setFont(font2);
        listWidget = new QListWidget(centralwidget);
        listWidget->setObjectName(QString::fromUtf8("listWidget"));
        listWidget->setGeometry(QRect(790, 30, 300, 500));
        groupBox_4 = new QGroupBox(centralwidget);
        groupBox_4->setObjectName(QString::fromUtf8("groupBox_4"));
        groupBox_4->setGeometry(QRect(450, 360, 311, 171));
        groupBox_4->setFont(font1);
        label_27 = new QLabel(groupBox_4);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(200, 20, 61, 22));
        label_27->setFont(font3);
        label_27->setFocusPolicy(Qt::NoFocus);
        label_27->setLayoutDirection(Qt::LeftToRight);
        label_27->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        StepMoveCheckBox = new QCheckBox(groupBox_4);
        StepMoveCheckBox->setObjectName(QString::fromUtf8("StepMoveCheckBox"));
        StepMoveCheckBox->setEnabled(true);
        StepMoveCheckBox->setGeometry(QRect(170, 100, 75, 30));
        StepMoveCheckBox->setFont(font2);
        label_24 = new QLabel(groupBox_4);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(10, 50, 75, 22));
        label_24->setFont(font3);
        label_24->setFocusPolicy(Qt::NoFocus);
        label_24->setLayoutDirection(Qt::LeftToRight);
        label_24->setAlignment(Qt::AlignCenter);
        stopLayerPrintButton = new QPushButton(groupBox_4);
        stopLayerPrintButton->setObjectName(QString::fromUtf8("stopLayerPrintButton"));
        stopLayerPrintButton->setGeometry(QRect(170, 130, 90, 30));
        stopLayerPrintButton->setFont(font2);
        label_25 = new QLabel(groupBox_4);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(200, 50, 61, 22));
        label_25->setFont(font3);
        label_25->setFocusPolicy(Qt::NoFocus);
        label_25->setLayoutDirection(Qt::LeftToRight);
        label_25->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        startLayerPrintButton = new QPushButton(groupBox_4);
        startLayerPrintButton->setObjectName(QString::fromUtf8("startLayerPrintButton"));
        startLayerPrintButton->setGeometry(QRect(20, 130, 90, 30));
        startLayerPrintButton->setFont(font4);
        LayerNumberSpinBox = new QSpinBox(groupBox_4);
        LayerNumberSpinBox->setObjectName(QString::fromUtf8("LayerNumberSpinBox"));
        LayerNumberSpinBox->setGeometry(QRect(90, 80, 101, 22));
        LayerNumberSpinBox->setFont(font2);
        LayerNumberSpinBox->setMaximum(10000);
        VelocityMoveCheckBox = new QCheckBox(groupBox_4);
        VelocityMoveCheckBox->setObjectName(QString::fromUtf8("VelocityMoveCheckBox"));
        VelocityMoveCheckBox->setEnabled(true);
        VelocityMoveCheckBox->setGeometry(QRect(40, 100, 75, 30));
        VelocityMoveCheckBox->setFont(font2);
        LayerHeightDoubleSpinBox = new QDoubleSpinBox(groupBox_4);
        LayerHeightDoubleSpinBox->setObjectName(QString::fromUtf8("LayerHeightDoubleSpinBox"));
        LayerHeightDoubleSpinBox->setGeometry(QRect(90, 20, 101, 22));
        LayerHeightDoubleSpinBox->setFont(font2);
        LayerHeightDoubleSpinBox->setMaximum(250.000000000000000);
        StructHeightDoubleSpinBox = new QDoubleSpinBox(groupBox_4);
        StructHeightDoubleSpinBox->setObjectName(QString::fromUtf8("StructHeightDoubleSpinBox"));
        StructHeightDoubleSpinBox->setGeometry(QRect(90, 50, 101, 22));
        StructHeightDoubleSpinBox->setFont(font2);
        StructHeightDoubleSpinBox->setMaximum(250.000000000000000);
        label_15 = new QLabel(groupBox_4);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(10, 20, 75, 22));
        label_15->setFont(font3);
        label_15->setFocusPolicy(Qt::NoFocus);
        label_15->setLayoutDirection(Qt::LeftToRight);
        label_15->setAlignment(Qt::AlignCenter);
        label_26 = new QLabel(groupBox_4);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(10, 80, 75, 22));
        label_26->setFont(font3);
        label_26->setFocusPolicy(Qt::NoFocus);
        label_26->setLayoutDirection(Qt::LeftToRight);
        label_26->setAlignment(Qt::AlignCenter);
        label_28 = new QLabel(centralwidget);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(790, 10, 201, 16));
        label_28->setFont(font1);
        PrintProgressBar = new QProgressBar(centralwidget);
        PrintProgressBar->setObjectName(QString::fromUtf8("PrintProgressBar"));
        PrintProgressBar->setGeometry(QRect(450, 540, 341, 23));
        PrintProgressBar->setValue(0);
        savePatternConfigurationButton = new QPushButton(centralwidget);
        savePatternConfigurationButton->setObjectName(QString::fromUtf8("savePatternConfigurationButton"));
        savePatternConfigurationButton->setGeometry(QRect(970, 540, 90, 30));
        savePatternConfigurationButton->setFont(font2);
        loadPatternConfigurationButton = new QPushButton(centralwidget);
        loadPatternConfigurationButton->setObjectName(QString::fromUtf8("loadPatternConfigurationButton"));
        loadPatternConfigurationButton->setGeometry(QRect(820, 540, 90, 30));
        loadPatternConfigurationButton->setFont(font4);
        MainWindow->setCentralWidget(centralwidget);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "LayerPrinter", nullptr));
        ErrorLabel->setText(QCoreApplication::translate("MainWindow", "NO ERROR", nullptr));
        DebugButton->setText(QCoreApplication::translate("MainWindow", "\346\265\213\350\257\225\346\214\211\351\222\256", nullptr));
        status_groupBox->setTitle(QCoreApplication::translate("MainWindow", "Status", nullptr));
        internalMemTest_checkBox->setText(QCoreApplication::translate("MainWindow", "Internal Memory Test Passed", nullptr));
        incompatibleASICorDMD_checkBox->setText(QCoreApplication::translate("MainWindow", "Controller/DMD Incompatible", nullptr));
        slaveReady_checkBox->setText(QCoreApplication::translate("MainWindow", "Slave Present and Ready", nullptr));
        internalInit_checkBox->setText(QCoreApplication::translate("MainWindow", "Internal Initialization Complete ", nullptr));
        DMDResetWaveformControllerErr_checkBox->setText(QCoreApplication::translate("MainWindow", "DMD Reset Waveform Controller Error ", nullptr));
        forcedSwapErr_checkBox->setText(QCoreApplication::translate("MainWindow", "Forced Swap Error ", nullptr));
        seqAbortStatus_checkBox->setText(QCoreApplication::translate("MainWindow", "Sequencer Abort Status Flag Error", nullptr));
        seqErr_checkBox->setText(QCoreApplication::translate("MainWindow", "Sequencer Error ", nullptr));
        DMDParkStatus_checkBox->setText(QCoreApplication::translate("MainWindow", "DMD Micromirrors Parked", nullptr));
        sequencerRunState_checkBox->setText(QCoreApplication::translate("MainWindow", "Sequencer Running", nullptr));
        videoState_checkBox->setText(QCoreApplication::translate("MainWindow", "Video Running", nullptr));
        extSourceLocked_checkBox->setText(QCoreApplication::translate("MainWindow", "Locked to External Source", nullptr));
        DMDgroupBox->setTitle(QCoreApplication::translate("MainWindow", "DMD", nullptr));
        label->setText(QCoreApplication::translate("MainWindow", "\346\233\235\345\205\211\346\227\266\351\227\264", nullptr));
        expoTimeSpinBox->setSuffix(QString());
        label_2->setText(QCoreApplication::translate("MainWindow", "\346\232\227\345\205\211\346\227\266\351\227\264", nullptr));
        darkTimeSpinBox->setSuffix(QString());
        ClearPatternsButton->setText(QCoreApplication::translate("MainWindow", "\346\270\205\351\231\244\345\233\276\347\211\207", nullptr));
        UpdateLUTButton->setText(QCoreApplication::translate("MainWindow", "\344\270\212\344\274\240\345\233\276\347\211\207", nullptr));
        startPatSequenceButton->setText(QCoreApplication::translate("MainWindow", "\345\274\200  \345\247\213", nullptr));
        stopPatSequenceButton->setText(QCoreApplication::translate("MainWindow", "\345\201\234  \346\255\242", nullptr));
        pausePatSequenceButton->setText(QCoreApplication::translate("MainWindow", "\346\232\202  \345\201\234", nullptr));
        AddPatternsButton->setText(QCoreApplication::translate("MainWindow", "\346\267\273\345\212\240\345\233\276\347\211\207", nullptr));
        DMDConnectCheckBox->setText(QCoreApplication::translate("MainWindow", "\346\234\252\350\277\236\346\216\245", nullptr));
        DMDConnectButton->setText(QCoreApplication::translate("MainWindow", "DMD\350\277\236\346\216\245", nullptr));
        DMDRepeatCheckBox->setText(QCoreApplication::translate("MainWindow", "\351\207\215\345\244\215\346\222\255\346\224\276", nullptr));
        DMDPlayOnceCheckBox->setText(QCoreApplication::translate("MainWindow", "\344\270\200\346\254\241\346\222\255\346\224\276", nullptr));
        DMDTrigInCheckBox->setText(QCoreApplication::translate("MainWindow", "TrigIn", nullptr));
        DMDTrigOutCheckBox->setText(QCoreApplication::translate("MainWindow", "TrigOut", nullptr));
        stageGroupBox->setTitle(QCoreApplication::translate("MainWindow", "\344\275\215\347\247\273\345\217\260", nullptr));
        groupBox->setTitle(QString());
        zPosLabel->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        label_4->setText(QCoreApplication::translate("MainWindow", "\344\275\215\347\275\256", nullptr));
        label_12->setText(QCoreApplication::translate("MainWindow", "um", nullptr));
        label_3->setText(QCoreApplication::translate("MainWindow", "\346\255\245\351\225\277", nullptr));
        label_5->setText(QCoreApplication::translate("MainWindow", "Z\350\275\264", nullptr));
        zAddButton->setText(QCoreApplication::translate("MainWindow", "+", nullptr));
        zMinusButton->setText(QCoreApplication::translate("MainWindow", "-", nullptr));
        label_16->setText(QCoreApplication::translate("MainWindow", "\347\233\256\346\240\207\344\275\215\347\275\256", nullptr));
        label_17->setText(QCoreApplication::translate("MainWindow", "um", nullptr));
        label_18->setText(QCoreApplication::translate("MainWindow", "um/s", nullptr));
        label_19->setText(QCoreApplication::translate("MainWindow", "\351\200\237\345\272\246\346\250\241\345\274\217", nullptr));
        zVelocityMoveButton->setText(QCoreApplication::translate("MainWindow", "MOVE", nullptr));
        zStopButton->setText(QCoreApplication::translate("MainWindow", "STOP", nullptr));
        zTargetMoveButton->setText(QString());
        groupBox_2->setTitle(QString());
        xPosLabel->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        label_8->setText(QCoreApplication::translate("MainWindow", "\346\255\245\351\225\277", nullptr));
        label_7->setText(QCoreApplication::translate("MainWindow", "\344\275\215\347\275\256", nullptr));
        label_13->setText(QCoreApplication::translate("MainWindow", "um", nullptr));
        label_6->setText(QCoreApplication::translate("MainWindow", "X\350\275\264", nullptr));
        xMinusButton->setText(QCoreApplication::translate("MainWindow", "-", nullptr));
        xAddButton->setText(QCoreApplication::translate("MainWindow", "+", nullptr));
        label_20->setText(QCoreApplication::translate("MainWindow", "um", nullptr));
        label_21->setText(QCoreApplication::translate("MainWindow", "\347\233\256\346\240\207\344\275\215\347\275\256", nullptr));
        xTargetMoveButton->setText(QString());
        groupBox_3->setTitle(QString());
        yPosLabel->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        label_14->setText(QCoreApplication::translate("MainWindow", "um", nullptr));
        label_11->setText(QCoreApplication::translate("MainWindow", "Y\350\275\264", nullptr));
        label_9->setText(QCoreApplication::translate("MainWindow", "\346\255\245\351\225\277", nullptr));
        label_10->setText(QCoreApplication::translate("MainWindow", "\344\275\215\347\275\256", nullptr));
        yMinusButton->setText(QCoreApplication::translate("MainWindow", "-", nullptr));
        yAddButton->setText(QCoreApplication::translate("MainWindow", "+", nullptr));
        yTargetMoveButton->setText(QString());
        label_22->setText(QCoreApplication::translate("MainWindow", "\347\233\256\346\240\207\344\275\215\347\275\256", nullptr));
        label_23->setText(QCoreApplication::translate("MainWindow", "um", nullptr));
        stageConnectCheckBox->setText(QCoreApplication::translate("MainWindow", "\346\234\252\350\277\236\346\216\245", nullptr));
        stageConnectButton->setText(QCoreApplication::translate("MainWindow", "\344\275\215\347\247\273\345\217\260\350\277\236\346\216\245", nullptr));
        groupBox_4->setTitle(QCoreApplication::translate("MainWindow", "\350\201\224\345\212\250", nullptr));
        label_27->setText(QCoreApplication::translate("MainWindow", "um", nullptr));
        StepMoveCheckBox->setText(QCoreApplication::translate("MainWindow", "\345\210\206\346\255\245\346\250\241\345\274\217", nullptr));
        label_24->setText(QCoreApplication::translate("MainWindow", "\347\273\223\346\236\204\351\253\230\345\272\246", nullptr));
        stopLayerPrintButton->setText(QCoreApplication::translate("MainWindow", "\345\201\234  \346\255\242", nullptr));
        label_25->setText(QCoreApplication::translate("MainWindow", "um", nullptr));
        startLayerPrintButton->setText(QCoreApplication::translate("MainWindow", "\345\274\200  \345\247\213", nullptr));
        LayerNumberSpinBox->setSuffix(QString());
        VelocityMoveCheckBox->setText(QCoreApplication::translate("MainWindow", "\351\200\237\345\272\246\346\250\241\345\274\217", nullptr));
        label_15->setText(QCoreApplication::translate("MainWindow", "\346\257\217\345\261\202\351\253\230\345\272\246", nullptr));
        label_26->setText(QCoreApplication::translate("MainWindow", "\347\273\223\346\236\204\345\261\202\346\225\260", nullptr));
        label_28->setText(QCoreApplication::translate("MainWindow", "\345\233\276\347\211\207\351\242\204\350\247\210", nullptr));
        savePatternConfigurationButton->setText(QCoreApplication::translate("MainWindow", "SAVE", nullptr));
        loadPatternConfigurationButton->setText(QCoreApplication::translate("MainWindow", "LOAD", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
